                                
								-----LAB 8------



-- 1. CREATE STUDENT TABLE
CREATE TABLE STUDENT1 (
    RNO INT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    BRANCH VARCHAR(50) NOT NULL
);

-- 2. INSERT DATA INTO STUDENT
INSERT INTO STUDENT1 (RNO, NAME, BRANCH) VALUES
(101, 'RAJU', 'CE'),
(102, 'AMIT', 'CE'),
(103, 'SANJAY', 'ME'),
(104, 'NEHA', 'EC'),
(105, 'MEERA', 'EE'),
(106, 'MAHESH', 'ME');

-- 3. CREATE RESULT TABLE
CREATE TABLE RESULT (
    RNO INT NULL,
    SPI DECIMAL(4,2) NOT NULL,
);

-- 4. INSERT DATA INTO RESULT
INSERT INTO RESULT (RNO, SPI) VALUES
(101, 8.8),
(102, 9.2),
(103, 7.6),
(104, 8.2),
(105, 7.0),
(107, 8.9);  

SELECT *FROM STUDENT1
SELECT * FROM RESULT

					----Part – A-----

--1. Create a stored procedure to perform Insert, Update, and Delete operations for both tables.
----INSERT
CREATE OR ALTER PROCEDURE PR_INSERT_STUDENT1
@RNO INT,
@NAME VARCHAR(50),
@BRANCH VARCHAR(50)
AS
BEGIN 
   INSERT INTO STUDENT1(RNO,NAME,BRANCH) VALUES(@RNO,@NAME,@BRANCH)
END
SELECT*FROM STUDENT1

EXEC PR_INSERT_STUDENT1 107,'RAM','CE'

----INSERT

CREATE OR ALTER PROCEDURE PR_INSERT_RESULT
	@RNO INT,
	@SPI DECIMAL(4,2)
AS
BEGIN
	INSERT INTO RESULT VALUES(@RNO,@SPI)
END

EXEC PR_INSERT_RESULT 108,9.0;
SELECT*FROM RESULT

----UPDATE

CREATE OR ALTER PROCEDURE PR_UPDATE_STUDENT1
	@RNO INT,
	@NAME VARCHAR(50)
	
AS
BEGIN
	UPDATE STUDENT1
	SET RNO=@RNO,NAME=@NAME,BRANCH=@BRANCH	
	WHERE RNO=@RNO
END

EXEC PR_UPDATE_STUDENT1 104, 'BHAKTIBA','CE';
SELECT*FROM STUDENT1

-----UPDATE

CREATE OR ALTER PROCEDURE PR_UPDATE_RESULT
	@RNO INT,
	@SPI DECIMAL(4,2)
AS
BEGIN
	UPDATE RESULT
	SET RNO=@RNO,SPI=@SPI
	WHERE RNO=@RNO
END

EXEC PR_UPDATE_RESULT 105,8.00;
SELECT*FROM RESULT

----DELETE

CREATE OR ALTER PROCEDURE PR_DELETE_STUDENT1
	@RNO INT,
	@NAME VARCHAR(50),
	@BRANCH VARCHAR(50)
AS
BEGIN
	DELETE FROM STUDENT1
	WHERE RNO=@RNO
END

EXEC PR_DELETE_STUDENT1 107,'DEF','CE';

SELECT*FROM STUDENT1

---DELETE

CREATE OR ALTER PROCEDURE PR_DELETE_RESULT
	@RNO INT,
	@SPI DECIMAL(4,2)
AS
BEGIN
	DELETE FROM RESULT
	WHERE RNO=@RNO
END

EXEC PR_DELETE_RESULT 103,7.6;

SELECT * FROM RESULT


--2. Create a stored procedure to perform SelectPK for both tables.
CREATE PROCEDURE PR_SELECTPK_STUDENT1
	@RNO INT
AS
BEGIN
	SELECT * FROM STUDENT1
	WHERE RNO=@RNO
END

EXEC PR_SELECTPK_STUDENT1 104;

SELECT * FROM STUDENT1
----

CREATE OR ALTER PROCEDURE PR_SELECTPK_RESULT
	@RNO INT
AS
BEGIN
	SELECT * FROM RESULT
	WHERE RNO=@RNO
END

EXEC PR_SELECTPK_RESULT 104;--DATA SHOWS OF 104

SELECT * FROM RESULT

--3. Create a stored procedure to perform SelectAll for both tables.
CREATE OR ALTER PROCEDURE PR_SELECTALL_STUDENT1
AS
BEGIN
	SELECT * FROM STUDENT1
END

EXEC PR_SELECTALL_STUDENT1 

SELECT * FROM STUDENT1

----

CREATE OR ALTER PROCEDURE PR_SELECTALL_RESULT
AS
BEGIN 
    SELECT * FROM RESULT
END

EXEC PR_SELECTALL_RESULT

SELECT * FROM RESULT


             ----Part – B----

--4. Create a stored procedure that takes branch as input and returns a table with all the students studying in that department.
CREATE OR ALTER PROCEDURE PR_STUDY_DEPARTMENT
	@BRANCH VARCHAR(50)
AS
BEGIN
	SELECT * FROM STUDENT1
	WHERE @BRANCH=BRANCH
END

EXEC PR_STUDY_DEPARTMENT 'CE';

--5. Create a stored procedure to display Rno, Name and SPI of first 2 students only.
CREATE OR ALTER PROCEDURE PR_FIRST_2_STUDENT
AS
BEGIN
	SELECT TOP 2 S.RNO , S.NAME , R.SPI
	FROM STUDENT1 S JOIN RESULT R
	ON S.RNO=R.RNO
	ORDER BY SPI DESC
END

EXEC PR_FIRST_2_STUDENT ;

     
-----------------------Part – C 

--6. Create a stored procedure which displays top 5 students based on SPI in descending order.  
CREATE OR ALTER PROCEDURE PR_FIRST_5_STUDENT
AS
BEGIN
	SELECT TOP 5 S.RNO , S.NAME , R.SPI
	FROM STUDENT1 S JOIN RESULT R
	ON S.RNO=R.RNO
	ORDER BY SPI DESC
END

EXEC PR_FIRST_5_STUDENT ; 

--7. Create a stored procedure which displays branch wise maximum and minimum SPI.
CREATE OR ALTER PROCEDURE PR_MAX_MIN_SPI
AS
BEGIN
	SELECT S.BRANCH , MAX(R.SPI) AS MAXIMUM , MIN(R.SPI)AS MINIMUM
	FROM STUDENT1 S JOIN RESULT R
	ON S.RNO=R.RNO
	GROUP BY S.BRANCH
END

EXEC PR_MAX_MIN_SPI
